### ISSUE TITLE
Unable to run introduction tutorial

### ISSUE THREAD

**Issue by alabarga** [theislab/ehrapy-tutorials#17]
Running this section of the tutorial

```
data = {
    "Column1": ["Apple", "Banana", "Cherry", "Date"])
    "Column2": [10, 20, 15, 5],
    "Column3": [True, False, True, False],
    "Column4": [
        pd.Timestamp("2023-08-01"),
        pd.Timestamp("2023-08-15"),
        pd.Timestamp("2023-08-10"),
        pd.Timestamp("2023-08-05"),
    ],
    "Column5": pd.Categorical(["dead", "alive", "dead", "dead"]),
}

df = pd.DataFrame(data)
df

adata = ep.ad.df_to_anndata(df)
adata

```

produces following error
`
ValueError: could not convert string to float: 'Apple'`

using versions:

- ehrapy '0.6.0'
- anndata '0.8.0'

**Comment by Zethson** [comment]
Huh, I'll look into it!

**Comment by Zethson** [comment]
![image](https://github.com/theislab/ehrapy-tutorials/assets/21954664/36f7fdba-327c-42c6-a8be-62f920e1b9e8)
I just tested it again.

Would it be possible for you to create a new environment, install ehrapy in it and try again? I fear that your anndata version isn't the latest and your Pandas version might not be either.

**Comment by Zethson** [comment]
We're also running this notebook as part of our CI: https://github.com/theislab/ehrapy/actions/runs/7533074715/job/20504918714 and it's always working

**Comment by alabarga** [comment]
Upgradin anndata to version '0.10.4' made the trick. Thank you so much!

**Comment by Zethson** [comment]
Great! I'd encourage you to open issues if you have feature requests or run into bugs. This is very early stage and we're happy to take feedback.
